Primera csp limitations
hpe-storage/csi-driver pull request #239
Opened 2021-01-22 11:27 UTC by wdurairaj

2021-01-22 13:23 UTC, suneeth51 requested changes

2021-01-22 13:23 UTC, suneeth51 commented on release-notes/v1.4.0.md
> +|CIDG-1305|Volume Mutator| Error validation in multiple edits | If multipled fields of PVC are edited, and if one of them is incorrect, partial edits are not done, and it results in a failure. `kubec
nit: `If multiple fields of PVC are edited`

2021-01-22 13:23 UTC, suneeth51 commented on release-notes/v1.4.0.md
> +||Volume Mutator| Incorrect PVC edit| If there is a validation failure due to incorrect PVC edit, then the operation does'nt stop until the user corrects the edit operation. This is a limitation for
nit: `then the operation does not stop`

2021-01-22 13:23 UTC, suneeth51 commented on release-notes/v1.4.0.md
> +||Replication| System limitation|Handling system limtation of RCG| If more than 60 volumes are added into a RCG (Remote Copy Group) as part of parallel volume addition, due to the stop/start of RCG i
nit: `limitation of RCG`

nit: `Limit the number of PVCs to be added ...`

2021-01-25 15:19 UTC, wdurairaj commented
@suneeth51 , hi , request you to review the recent changes.

Thanks.

2021-01-25 15:58 UTC, suneeth51 approved these changes
lgtm with one more minor comment.

2021-01-25 15:58 UTC, suneeth51 commented on release-notes/v1.4.0.md
> +||Replication| System limitation|Handling system limtation of RCG| If more than 60 volumes are added into a RCG (Remote Copy Group) as part of parallel volume addition, due to the stop/start of RCG i
nit: typo `limitation`

2021-01-25 16:21 UTC, wdurairaj commented on release-notes/v1.4.0.md
> +||Replication| System limitation|Handling system limtation of RCG| If more than 60 volumes are added into a RCG (Remote Copy Group) as part of parallel volume addition, due to the stop/start of RCG i
Done.. Good catch :)

2021-01-25 20:17 UTC, raunakkumar requested changes

2021-01-25 20:17 UTC, raunakkumar commented on release-notes/v1.4.0.md
> +|CIDG-1928|Volume Groups | Volume group deletion|Volume group can be deleted even though some PVC's are still associated to it | Due to a limitation in volume group sidecar, we are not able to preven
Can we mention that the volume group CR gets deleted but the a volume group content and the storage backed volume group remains ?

2021-01-25 20:17 UTC, raunakkumar commented on release-notes/v1.4.0.md
> +||Volume Mutator| Incorrect PVC edit| If there is a validation failure due to incorrect PVC edit, then the operation does not stop until the user corrects the edit operation. This is a limitation for
It is possible to associate a bug id for the last 2 Notes?

2021-02-01 18:36 UTC, raunakkumar commented
@wdurairaj Any update on this PR?

2021-02-01 19:18 UTC, raunakkumar approved these changes
lgtm

2021-02-01 19:19 UTC, merged