Handling the ISCSI and Multipath configuration in node init container
hpe-storage/csi-driver pull request #411
Opened 2024-07-09 19:10 UTC by AnushaY1916

2024-07-09 23:31 UTC, datamattsson requested changes
Can we fix L132-133 in this PR to read better? This is what the log entry looks like:

```
time="2024-07-09T23:25:35Z" level=info msg="Node configuration is disabled, DISABLE_NODE_CONFIGURATION=true.Skipping the Multipath and ISCSI configurations" file="csi-driver.go:132"
```

Something like this:
```
				" Skipping node configuration. All block storage services needs to be installed and configured manually.", disableNodeConfiguraton)
```

2024-07-10 04:11 UTC, dileepds approved these changes
LGTM

2024-07-10 04:29 UTC, sijeesh approved these changes
LGTM

2024-07-10 22:46 UTC, datamattsson approved these changes

2024-07-11 03:02 UTC, merged